if not SGO or not SGO.settings.use_perka then return end
local data = SkillTreeTweakData.init
function SkillTreeTweakData:init(tweak_data)
	data(self, tweak_data)
--1.Crew Chief

table.insert(self.specializations[1][9].upgrades, "body_armor6")
table.insert(self.specializations[1][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[1][9].upgrades, "second_deployable_1")
table.insert(self.specializations[1][7].upgrades, "player_shield_knock")
table.insert(self.specializations[1][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[1][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[1][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[1][7].upgrades, "second_deployable_1")
table.insert(self.specializations[1][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
table.insert(self.specializations[1][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[1][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[1][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[1][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[1][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[1][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[1][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[1][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[1][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[1][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[1][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[1][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[1][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[1][1].upgrades, "saw_secondary")
table.insert(self.specializations[1][9].upgrades, "player_hostage_health_regen_addend_1")
table.insert(self.specializations[1][9].upgrades, "player_hostage_health_regen_addend_2")

--Muscle

table.insert(self.specializations[2][9].upgrades, "body_armor6")
table.insert(self.specializations[2][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[2][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[2][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[2][9].upgrades, "second_deployable_1")
table.insert(self.specializations[2][7].upgrades, "player_shield_knock")
table.insert(self.specializations[2][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[2][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[2][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[2][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
table.insert(self.specializations[2][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[2][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[2][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[2][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[2][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[2][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[2][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[2][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[2][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[2][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[2][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[2][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[2][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[2][1].upgrades, "saw_secondary")
table.insert(self.specializations[2][9].upgrades, "player_hostage_health_regen_addend_1")
table.insert(self.specializations[2][9].upgrades, "player_hostage_health_regen_addend_2")

--3.Armorer

table.insert(self.specializations[3][9].upgrades, "body_armor6")
table.insert(self.specializations[3][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[3][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[3][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[3][9].upgrades, "second_deployable_1")
table.insert(self.specializations[3][9].upgrades, "player_cheat_death_chance_1")
table.insert(self.specializations[3][9].upgrades, "player_cheat_death_chance_2")
table.insert(self.specializations[3][9].upgrades, "player_additional_lives_1")
table.insert(self.specializations[3][7].upgrades, "player_shield_knock")
table.insert(self.specializations[3][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[3][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[3][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
table.insert(self.specializations[3][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[3][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[3][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[3][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[3][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[3][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[3][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[3][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[3][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[3][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[3][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[3][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[3][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[3][1].upgrades, "saw_secondary")

--4.Rogue (dodge alert)

table.insert(self.specializations[4][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[4][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[4][9].upgrades, "player_cheat_death_chance_1")
table.insert(self.specializations[4][9].upgrades, "player_cheat_death_chance_2")
table.insert(self.specializations[4][9].upgrades, "second_deployable_1")
table.insert(self.specializations[4][7].upgrades, "player_shield_knock")
table.insert(self.specializations[4][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[4][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[4][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[4][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
table.insert(self.specializations[4][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[4][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[4][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[4][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[4][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[4][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[4][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[4][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[4][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[4][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[4][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[4][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[4][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[4][1].upgrades, "saw_secondary")

--5.Hitman --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[5][9].upgrades, "body_armor6")
table.insert(self.specializations[5][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[5][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[5][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[5][9].upgrades, "player_cheat_death_chance_1")
table.insert(self.specializations[5][9].upgrades, "player_cheat_death_chance_2")
table.insert(self.specializations[5][9].upgrades, "player_additional_lives_1")
table.insert(self.specializations[5][7].upgrades, "player_shield_knock")
table.insert(self.specializations[5][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[5][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[5][7].upgrades, "second_deployable_1")
table.insert(self.specializations[5][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
table.insert(self.specializations[5][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[5][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[5][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[5][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[5][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[5][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[5][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[5][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[5][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[5][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[5][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[5][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[5][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[5][1].upgrades, "saw_secondary")

--6.Crook (Armored dodge) --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[6][9].upgrades, "body_armor6")
table.insert(self.specializations[6][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[6][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[6][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[6][9].upgrades, "player_cheat_death_chance_1")
table.insert(self.specializations[6][9].upgrades, "player_cheat_death_chance_2")
table.insert(self.specializations[6][9].upgrades, "player_additional_lives_1")
table.insert(self.specializations[6][7].upgrades, "player_shield_knock")
table.insert(self.specializations[6][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[6][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[6][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[6][7].upgrades, "second_deployable_1")
table.insert(self.specializations[6][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
table.insert(self.specializations[6][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[6][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[6][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[6][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[6][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[6][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[6][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[6][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[6][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[6][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[6][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[6][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[6][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[6][1].upgrades, "saw_secondary")

--7.Burglar (Clover) --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[7][9].upgrades, "body_armor6")
table.insert(self.specializations[7][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[7][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[7][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[7][9].upgrades, "player_cheat_death_chance_1")
table.insert(self.specializations[7][9].upgrades, "player_cheat_death_chance_2")
table.insert(self.specializations[7][9].upgrades, "player_additional_lives_1")
table.insert(self.specializations[7][7].upgrades, "player_shield_knock")
table.insert(self.specializations[7][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[7][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[7][7].upgrades, "second_deployable_1")
table.insert(self.specializations[7][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
table.insert(self.specializations[7][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[7][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[7][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[7][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[7][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[7][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[7][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[7][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[7][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[7][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[7][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[7][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[7][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[7][1].upgrades, "saw_secondary")

--8.Infiltrator (Dragan) --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[8][9].upgrades, "body_armor6")
table.insert(self.specializations[8][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[8][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[8][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[8][9].upgrades, "player_tier_armor_multiplier_4")
table.insert(self.specializations[8][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[8][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[8][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[8][7].upgrades, "second_deployable_1")
table.insert(self.specializations[8][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
table.insert(self.specializations[8][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[8][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[8][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[8][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[8][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[8][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[8][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[8][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[8][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[8][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[8][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[8][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[8][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[8][1].upgrades, "saw_secondary")

--9.Sociopath (Jacket) --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[9][9].upgrades, "body_armor6")
table.insert(self.specializations[9][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[9][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[9][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[9][9].upgrades, "player_tier_armor_multiplier_4")
table.insert(self.specializations[9][7].upgrades, "player_shield_knock")
table.insert(self.specializations[9][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[9][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[9][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[9][7].upgrades, "second_deployable_1")
table.insert(self.specializations[9][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[9][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[9][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[9][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[9][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[9][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[9][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[9][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[9][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[9][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[9][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[9][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[9][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[9][1].upgrades, "saw_secondary")

--10.Gambler --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[10][9].upgrades, "body_armor6")
table.insert(self.specializations[10][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[10][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[10][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[10][9].upgrades, "second_deployable_1")
table.insert(self.specializations[10][7].upgrades, "player_shield_knock")
table.insert(self.specializations[10][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[10][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[10][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[10][7].upgrades, "second_deployable_1")
table.insert(self.specializations[10][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[10][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[10][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[10][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[10][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[10][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[10][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[10][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[10][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[10][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[10][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[10][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[10][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[10][1].upgrades, "saw_secondary")

--11.Grinder (Sokol)--ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[11][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[11][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[11][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[11][9].upgrades, "second_deployable_1")
table.insert(self.specializations[11][7].upgrades, "player_shield_knock")
table.insert(self.specializations[11][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[11][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[11][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[11][7].upgrades, "second_deployable_1")
table.insert(self.specializations[11][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[11][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[11][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[11][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[11][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[11][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[11][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[11][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[11][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[11][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[11][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[11][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[11][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[11][1].upgrades, "saw_secondary")

--12.Yakuza (Jiro) --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[12][9].upgrades, "body_armor6")
table.insert(self.specializations[12][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[12][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[12][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[12][9].upgrades, "player_tier_armor_multiplier_4")
table.insert(self.specializations[12][7].upgrades, "player_shield_knock")
table.insert(self.specializations[12][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[12][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[12][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[12][7].upgrades, "second_deployable_1")
table.insert(self.specializations[12][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[12][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[12][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[12][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[12][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[12][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[12][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[12][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[12][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[12][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[12][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[12][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[12][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[12][1].upgrades, "saw_secondary")

--13.Ex President (Bodhi) --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[13][9].upgrades, "body_armor6")
table.insert(self.specializations[13][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[13][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[13][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[13][7].upgrades, "player_shield_knock")
table.insert(self.specializations[13][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[13][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[13][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[13][7].upgrades, "second_deployable_1")
table.insert(self.specializations[13][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
table.insert(self.specializations[13][6].upgrades, "pistol_reload_speed_multiplier")
table.insert(self.specializations[13][6].upgrades, "temporary_single_shot_fast_reload_1")
table.insert(self.specializations[13][6].upgrades, "assault_rifle_reload_speed_multiplier")
table.insert(self.specializations[13][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[13][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[13][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[13][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[13][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[13][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[13][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[13][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[13][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[13][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[13][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[13][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[13][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[13][1].upgrades, "saw_secondary")

--14.Maniac --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[14][9].upgrades, "body_armor6")
table.insert(self.specializations[14][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[14][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[14][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[14][9].upgrades, "player_tier_armor_multiplier_4")
table.insert(self.specializations[14][7].upgrades, "player_shield_knock")
table.insert(self.specializations[14][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[14][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[14][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[14][7].upgrades, "second_deployable_1")
table.insert(self.specializations[14][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[14][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[14][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[14][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[14][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[14][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[14][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[14][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[14][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[14][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[14][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[14][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[14][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[14][1].upgrades, "saw_secondary")

--15.Anarchist --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[15][9].upgrades, "body_armor6")
table.insert(self.specializations[15][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[15][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[15][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[15][9].upgrades, "player_tier_armor_multiplier_4")
table.insert(self.specializations[15][7].upgrades, "player_shield_knock")
table.insert(self.specializations[15][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[15][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[15][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[15][7].upgrades, "second_deployable_1")
table.insert(self.specializations[15][6].upgrades, "player_cheat_death_chance_1")
table.insert(self.specializations[15][6].upgrades, "player_cheat_death_chance_2")
table.insert(self.specializations[15][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[15][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[15][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[15][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[15][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[15][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[15][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[15][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[15][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[15][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[15][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[15][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[15][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[15][1].upgrades, "saw_secondary")

--16.Biker --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[16][9].upgrades, "body_armor6")
table.insert(self.specializations[16][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[16][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[16][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[16][9].upgrades, "player_cheat_death_chance_1")
table.insert(self.specializations[16][9].upgrades, "player_cheat_death_chance_2")
table.insert(self.specializations[16][9].upgrades, "player_tier_armor_multiplier_4")
table.insert(self.specializations[16][7].upgrades, "player_shield_knock")
table.insert(self.specializations[16][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[16][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[16][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[16][7].upgrades, "second_deployable_1")
table.insert(self.specializations[16][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
table.insert(self.specializations[16][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[16][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[16][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[16][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[16][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[16][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[16][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[16][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[16][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[16][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[16][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[16][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[16][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[16][1].upgrades, "saw_secondary")

--17.Kingpin --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[17][9].upgrades, "body_armor6")
table.insert(self.specializations[17][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[17][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[17][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[17][9].upgrades, "player_cheat_death_chance_1")
table.insert(self.specializations[17][9].upgrades, "player_cheat_death_chance_2")
table.insert(self.specializations[17][9].upgrades, "player_tier_armor_multiplier_4")
table.insert(self.specializations[17][7].upgrades, "player_shield_knock")
table.insert(self.specializations[17][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[17][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[17][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[17][7].upgrades, "second_deployable_1")
table.insert(self.specializations[17][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
table.insert(self.specializations[17][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[17][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[17][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[17][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[17][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[17][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[17][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[17][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[17][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[17][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[17][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[17][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[17][2].upgrades, "player_chico_armor_multiplier_1")
table.insert(self.specializations[17][2].upgrades, "player_chico_armor_multiplier_2")
table.insert(self.specializations[17][2].upgrades, "player_chico_armor_multiplier_1")
table.insert(self.specializations[17][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[17][1].upgrades, "saw_secondary")

--18.Sicario --ICTV+Throwables pickup+SwapSpeed+1Messiah+Armorer Invulnerability+

table.insert(self.specializations[18][9].upgrades, "body_armor6")
table.insert(self.specializations[18][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[18][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[18][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[18][9].upgrades, "player_cheat_death_chance_1")
table.insert(self.specializations[18][9].upgrades, "player_cheat_death_chance_2")
table.insert(self.specializations[18][9].upgrades, "player_tier_armor_multiplier_4")
table.insert(self.specializations[18][7].upgrades, "player_shield_knock")
table.insert(self.specializations[18][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[18][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[18][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[18][7].upgrades, "second_deployable_1")
table.insert(self.specializations[18][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
table.insert(self.specializations[18][4].upgrades, "deploy_interact_faster_1")
table.insert(self.specializations[18][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[18][3].upgrades, "player_overkill_all_weapons")
table.insert(self.specializations[18][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[18][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[18][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[18][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[18][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[18][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[18][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[18][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[18][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[18][2].upgrades, "player_chico_armor_multiplier_1")
table.insert(self.specializations[18][2].upgrades, "player_chico_armor_multiplier_2")
table.insert(self.specializations[18][2].upgrades, "player_chico_armor_multiplier_1")
table.insert(self.specializations[18][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[18][1].upgrades, "saw_secondary")

--This is kinda special
table.insert(self.specializations[1][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[2][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[3][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[4][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[5][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[6][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[7][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[8][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[9][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[10][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[11][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[12][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[13][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[14][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[15][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[16][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[17][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[18][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[1][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[1][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[1][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[1][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[2][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[2][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[2][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[2][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[3][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[3][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[3][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[3][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[4][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[4][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[4][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[4][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[5][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[5][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[5][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[5][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[6][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[6][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[6][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[6][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[7][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[7][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[7][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[7][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[8][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[8][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[8][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[8][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[9][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[9][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[9][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[9][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[10][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[10][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[10][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[10][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[11][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[11][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[11][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[11][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[12][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[12][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[12][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[12][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[13][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[13][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[13][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[13][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[14][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[14][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[14][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[14][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[16][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[16][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[16][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[16][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[17][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[17][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[17][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[17][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[18][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[18][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[18][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[18][1].upgrades, "player_passive_health_multiplier_4")

--Previous Sync System
table.insert(self.specializations[1][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[1][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[1][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[1][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[1][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[1][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[1][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[1][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[1][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[1][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[1][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[2][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[2][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[2][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[2][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[2][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[2][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[2][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[2][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[2][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[2][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[2][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[3][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[3][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[3][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[3][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[3][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[3][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[3][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[3][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[3][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[3][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[3][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[4][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[4][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[4][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[4][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[4][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[4][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[4][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[4][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[4][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[4][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[4][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[5][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[5][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[5][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[5][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[5][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[5][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[5][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[5][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[5][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[5][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[5][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[6][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[6][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[6][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[6][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[6][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[6][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[6][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[6][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[6][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[6][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[6][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[7][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[7][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[7][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[7][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[7][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[7][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[7][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[7][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[7][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[7][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[7][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[8][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[8][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[8][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[8][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[8][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[8][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[8][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[8][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[8][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[8][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[8][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[9][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[9][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[9][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[9][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[9][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[9][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[9][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[9][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[9][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[9][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[9][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[10][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[10][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[10][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[10][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[10][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[10][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[10][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[10][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[10][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[10][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[10][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[11][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[11][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[11][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[11][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[11][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[11][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[11][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[11][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[11][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[11][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[11][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[12][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[12][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[12][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[12][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[12][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[12][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[12][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[12][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[12][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[12][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[12][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[13][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[13][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[13][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[13][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[13][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[13][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[13][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[13][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[13][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[13][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[13][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[14][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[14][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[14][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[14][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[14][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[14][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[14][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[14][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[14][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[14][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[14][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[15][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[15][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[15][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[15][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[15][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[15][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[15][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[15][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[15][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[15][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[15][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[16][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[16][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[16][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[16][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[16][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[16][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[16][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[16][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[16][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[16][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[16][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[17][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[17][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[17][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[17][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[17][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[17][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[17][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[17][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[17][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[17][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[17][6].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[18][2].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[18][2].upgrades, "player_run_and_reload")
table.insert(self.specializations[18][2].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[18][2].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[18][4].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[18][4].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[18][4].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[18][4].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[18][6].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[18][6].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[18][6].upgrades, "player_recharge_messiah_1")

end

--[[
	"temporary_armor_break_invulnerable_1",
	"player_run_and_reload",
	"player_passive_always_regen_armor_1",
	"player_perk_armor_regen_timer_multiplier_1",
	"player_perk_armor_regen_timer_multiplier_2",
	"player_perk_armor_regen_timer_multiplier_3",
	"player_perk_armor_regen_timer_multiplier_4",
	"player_perk_armor_regen_timer_multiplier_5",
	"player_regain_throwable_from_ammo_1",
	"player_messiah_revive_from_bleed_out_1",
	"player_recharge_messiah_1"
Oi, dont touch this!
"player_marked_enemy_extra_damage",
"player_marked_inc_dmg_distance_1",
"player_hostage_health_regen_addend_1",
"player_hostage_health_regen_addend_2",
"player_counter_strike_melee",
"player_counter_strike_spooc",
"doctor_bag_quantity",
"doctor_bag_amount_increase1",
"ammo_bag_quantity",
"ammo_bag_ammo_increase1",

player_movement_speed_damage_health_ratio_multiplier"
"player_movement_speed_damage_health_ratio_threshold_multiplier
"player_movement_speed_damage_health_ratio_multiplier"

table.insert(self.specializations[][2].upgrades, "")
table.insert(self.specializations[][2].upgrades, "")
table.insert(self.specializations[][2].upgrades, "")
"player_perk_armor_regen_timer_multiplier_1"
"player_perk_armor_regen_timer_multiplier_2"
"player_perk_armor_regen_timer_multiplier_3"
"player_perk_armor_regen_timer_multiplier_4"
"player_perk_armor_regen_timer_multiplier_5"
"player_passive_always_regen_armor_1"
"team_passive_armor_regen_time_multiplier"
player_passive_health_multiplier_1 to 4
--]]
if not SystemFS:exists("mods/Seamlink Gameplay Overhaul/lua/assaulttweaks.lua")
or not SystemFS:exists("mods/Seamlink Gameplay Overhaul/lua/coplogicattack.lua")
or not SystemFS:exists("mods/Seamlink Gameplay Overhaul/lua/coplogicidle.lua")
or not SystemFS:exists("mods/Seamlink Gameplay Overhaul/lua/coplogictravel.lua")
or not SystemFS:exists("mods/Seamlink Gameplay Overhaul/lua/enemymanager.lua")
or not SystemFS:exists("mods/Seamlink Gameplay Overhaul/lua/groupaistatebase.lua")
or not SystemFS:exists("mods/Seamlink Gameplay Overhaul/lua/spooclogicattack.lua")
or not SystemFS:exists("mods/Seamlink Gameplay Overhaul/lua/tankcoplogicattack.lua")
or not SystemFS:exists("mods/Seamlink Gameplay Overhaul/lua/shieldlogicattack.lua")
or not SystemFS:exists("mods/Seamlink Gameplay Overhaul/lua/rebalanceissues.lua")
or not SystemFS:exists("mods/Seamlink Gameplay Overhaul/lua/sync.lua")
then
log("You have messed with SGO, reinstall it.")
	os.exit()
end

--[[

table.insert(self.specializations[1][9].upgrades, "body_armor6")
table.insert(self.specializations[1][9].upgrades, "player_regain_throwable_from_ammo_1")
table.insert(self.specializations[1][9].upgrades, "player_messiah_revive_from_bleed_out_1")
table.insert(self.specializations[1][9].upgrades, "player_recharge_messiah_1")
table.insert(self.specializations[1][9].upgrades, "weapon_swap_speed_multiplier")
table.insert(self.specializations[1][9].upgrades, "player_hostage_health_regen_addend_1")
table.insert(self.specializations[1][9].upgrades, "player_hostage_health_regen_addend_2")
table.insert(self.specializations[1][9].upgrades, "temporary_armor_break_invulnerable_1")
table.insert(self.specializations[1][9].upgrades, "second_deployable_1")
table.insert(self.specializations[1][9].upgrades, "saw_secondary")
table.insert(self.specializations[1][8].upgrades, "saw_ignore_shields_1")
table.insert(self.specializations[1][8].upgrades, "saw_extra_ammo_multiplier")
table.insert(self.specializations[1][8].upgrades, "player_saw_speed_multiplier_2")
table.insert(self.specializations[1][8].upgrades, "saw_lock_damage_multiplier_2")
table.insert(self.specializations[1][8].upgrades, "saw_enemy_slicer")
table.insert(self.specializations[1][8].upgrades, "saw_panic_when_kill_1")
table.insert(self.specializations[1][7].upgrades, "player_shield_knock")
table.insert(self.specializations[1][7].upgrades, "pistol_damage_addend_1")
table.insert(self.specializations[1][7].upgrades, "pistol_damage_addend_2")
table.insert(self.specializations[1][7].upgrades, "player_additional_lives_1")
table.insert(self.specializations[1][7].upgrades, "second_deployable_1")
table.insert(self.specializations[1][6].upgrades, "player_temp_melee_kill_increase_reload_speed_1")
--table.insert(self.specializations[1][6].upgrades, "pistol_reload_speed_multiplier")
--table.insert(self.specializations[1][6].upgrades, "temporary_single_shot_fast_reload_1")
--table.insert(self.specializations[1][6].upgrades, "assault_rifle_reload_speed_multiplier")
table.insert(self.specializations[1][5].upgrades, "sentry_gun_cost_reduction_1")
table.insert(self.specializations[1][5].upgrades, "sentry_gun_shield")
table.insert(self.specializations[1][5].upgrades, "sentry_gun_cost_reduction_2")
table.insert(self.specializations[1][5].upgrades, "sentry_gun_armor_multiplier")
table.insert(self.specializations[1][5].upgrades, "sentry_gun_silent")
table.insert(self.specializations[1][5].upgrades, "sentry_gun_ap_bullets")
table.insert(self.specializations[1][5].upgrades, "sentry_gun_damage_multiplier")
table.insert(self.specializations[1][5].upgrades, "sentry_gun_fire_rate_reduction_1")
table.insert(self.specializations[1][5].upgrades, "sentry_gun_quantity_1")
table.insert(self.specializations[1][5].upgrades, "sentry_gun_quantity_2")
table.insert(self.specializations[1][4].upgrades, "sentry_gun_spread_multiplier")
table.insert(self.specializations[1][4].upgrades, "sentry_gun_rot_speed_multiplier")
table.insert(self.specializations[1][4].upgrades, "sentry_gun_extra_ammo_multiplier_1")
table.insert(self.specializations[1][4].upgrades, "trip_mine_damage_multiplier_1")
table.insert(self.specializations[1][4].upgrades, "trip_mine_explosion_size_multiplier_1")
table.insert(self.specializations[1][4].upgrades, "trip_mine_quantity_increase_2")
table.insert(self.specializations[1][4].upgrades, "shape_charge_quantity_increase_2")
table.insert(self.specializations[1][4].upgrades, "trip_mine_quantity_increase_1")
table.insert(self.specializations[1][4].upgrades, "shape_charge_quantity_increase_1")
table.insert(self.specializations[1][4].upgrades, "deploy_interact_faster_1")
--table.insert(self.specializations[1][3].upgrades, "shotgun_reload_speed_multiplier_2")
table.insert(self.specializations[1][3].upgrades, "player_overkill_damage_multiplier")
table.insert(self.specializations[1][3].upgrades, "player_overkill_all_weapons")
--table.insert(self.specializations[1][3].upgrades, "shotgun_reload_speed_multiplier_1")
--table.insert(self.specializations[1][3].upgrades, "shotgun_enter_steelsight_speed_multiplier")
table.insert(self.specializations[1][3].upgrades, "shotgun_damage_multiplier_1")
table.insert(self.specializations[1][3].upgrades, "shotgun_damage_multiplier_2")
table.insert(self.specializations[1][3].upgrades, "player_armor_carry_bonus_1")
table.insert(self.specializations[1][3].upgrades, "player_mark_enemy_time_multiplier")
table.insert(self.specializations[1][3].upgrades, "weapon_steelsight_highlight_specials")
table.insert(self.specializations[1][2].upgrades, "player_pick_lock_hard")
table.insert(self.specializations[1][2].upgrades, "player_pick_lock_easy_speed_multiplier_2")
table.insert(self.specializations[1][2].upgrades, "player_drill_fix_interaction_speed_multiplier")
table.insert(self.specializations[1][2].upgrades, "player_drill_melee_hit_restart_chance_1")
table.insert(self.specializations[1][2].upgrades, "trip_mine_fire_trap_1")
table.insert(self.specializations[1][2].upgrades, "trip_mine_fire_trap_2")
table.insert(self.specializations[1][1].upgrades, "player_perk_armor_regen_timer_multiplier_1")
table.insert(self.specializations[1][1].upgrades, "player_perk_armor_regen_timer_multiplier_2")
table.insert(self.specializations[1][1].upgrades, "player_perk_armor_regen_timer_multiplier_3")
table.insert(self.specializations[1][1].upgrades, "player_perk_armor_regen_timer_multiplier_4")
table.insert(self.specializations[1][1].upgrades, "player_perk_armor_regen_timer_multiplier_5")
table.insert(self.specializations[1][1].upgrades, "player_passive_always_regen_armor_1")
table.insert(self.specializations[1][1].upgrades, "team_passive_armor_regen_time_multiplier")
table.insert(self.specializations[1][1].upgrades, "player_hostage_health_regen_addend_1")
table.insert(self.specializations[1][1].upgrades, "player_hostage_health_regen_addend_2")
table.insert(self.specializations[1][1].upgrades, "player_passive_health_multiplier_1")
table.insert(self.specializations[1][1].upgrades, "player_passive_health_multiplier_2")
table.insert(self.specializations[1][1].upgrades, "player_passive_health_multiplier_3")
table.insert(self.specializations[1][1].upgrades, "player_passive_health_multiplier_4")
table.insert(self.specializations[1][1].upgrades, "player_run_and_reload")
--]]