legal_text = "PAYDAY 2 © 2015 Starbreeze ขอสงวนลิขสิทธิ์dfasfsdf PAYDAY 2 , Starbreeze สตูดิโอและโลโก้ Starbreeze เป็นเครื่องหมายการค้าหรือเครื่องหมายการค้าจดทะเบียนของ Starbreeze AB ในประเทศสวีเดนและประเทศอื่น ๆ เผยแพร่fasdfsadfasdfโดย 505 Games. 505 Games และ 505 Game Logo เป็นเครื่องหมายการค้าจดทะเบียนของ 505 Games S.r.l เครื่องหมายการค้าอื่นทั้งหมดที่เป็นทรัพย์สินของเจ้าขasdfasdfasfaองที่เกี่ยวข้อง",--PAYDAY 2 © 2015 Starbreeze AB. All rights reserved.  PAYDAY 2, PAYDAY, Starbreeze, Starbreeze Studios, and the Starbreeze logo are trademarks or registered trademarks of Starbreeze AB in Sweden and/or other countries. Published by 505 Games. 505 Games and the 505 Games logo are registered trademarks of 505 Games S.r.l. All other trademarks are the property of their respective owners.
menu_press_start = "กดปุ่มเพื่อเริ่มเล่นเasdfasdfasกม",--PRESS ANY KEY
menu_visit_forum3 = "กดปุ่มเพื่อเริ่มเล่นdfasdfasdfเกม",--PRESS ANY KEY
menu_or_press_any_xbox_button = "หรือ$NL;กดปุ่มใดก็ได้บน Xbox 360 Controller",--Or$NL;Press any button on your Xbox 360 Controller
menu_news_new = "ประชาสัมพันธ์",--News
menu_play_new = "เล่น",--Play
menu_crimenet = "เล่นหลายคน",--CRIME.NET
menu_crimenet_new = "เล่นหลายคน",--Play Online
menu_crimenet_help = "เล่นกับเพื่อนๆหรือนักปล้นจากทั่วโลก",--Log onto Crime.net.
menu_crimenet_offline = "เล่นคนเดียว",--CRIME.NET Offline
menu_crimenet_offline_new = "เล่นคนเดียว",--Play Offline
menu_crimenet_offline_help = "ลงปล้นแบบโชว์เดี่ยวหรือเล่นกับบอท",--Start Crime.net in offline mode.
menu_content_updates_new = "เนื้อหาดาวน์โหลดเพิ่มเติม",--Content Updates
menu_inventory = "คลังเก็บของ",--INVENTORY
menu_inventory_help = "เข้าคลังเก็บของของคุณ",--Access your inventory.
menu_player_inventory = "คลังเก็บของ",--INVENTORY.
menu_player_inventory_help = "เข้าคลังเก็บของของคุณ",--Access your inventory.
menu_player_inventory_new = "โปรไฟล์",--Profile
menu_steam_inventory_new = "ช่องเก็บของใน Steam",--Steam Inventory
menu_steam_inventory = " ช่องเก็บของใน Steam",--Steam Inventory
menu_steam_inventory_help = "เข้าช่องเก็บของใน Steamของคุณ",--Access your Steam Inventory.
menu_player_inventory_help = "เข้าช่องเก็บของใน Steamของคุณ",--Access your inventory.
menu_infamytree = "ระบบเลื่อนขั้น",--Infamy
menu_infamytree_help = "รีเลเวทและเก็บพ้อยเพื่อรับรางวัล",--Become infamous and spend your Infamy Points to get rewards.
menu_become_infamous = "เลื่อนขั้นให้สูงขั้น",--Become Infamous
menu_become_infamous_help = "เลื่อนขั้นให้สูงขั้นและรีเซ็ตเลเวลของคุณ",--Reset your profile and go up in rank.
menu_safehouse = "เซฟเฮ้าส์",--Safe house.
menu_safehouse_new= "เซฟเฮ้าส์",--Play Safehouse
menu_safehouse_help = "ไปที่แหล่งกบดานของแก๊ง",--Go to the safe house.
menu_content_updates = "เนื้อหาดาวน์โหลดเพิ่มเติม",--Content Updates
menu_content_updates_help = "ดูอัพเดตล่าสุดเกี่ยวกับเนื้อหาดาวน์โหลดเพิ่มเติม",--Check out the latest PAYDAY 2 content updates and history.
menu_visit_gamehub = "ศูนย์กลางชุมชน",--Gamehub
menu_visit_gamehub_help = "พูดคุยกับทีมงานสร้างเกมและนักปล้นทุกคน",--Come talk to us at OVERKILL and the other heisters in the best forum on earth.
menu_visit_forum_help = "พูดคุยกับทีมงานสร้างเกมและนักปล้นทุกคน",--Come talk to us at OVERKILL and the other heisters in the best forum on earth.
menu_visit_fbi_files = "ไฟล์ของหน่วยเอฟบีไอ",--FBI Files
menu_visit_fbi_files_help = "แฮกเข้าระบบไฟล์เอฟบีไอเพื่อดูข้อมูล",--Hack into FBI.
menu_options = "ตั้งค่า",--OPTIONS BUTTON
menu_options_help = "ปรับเปลี่ยนการตั้งค่าของเกม",--Change your preferences and game settings.
menu_credits = "ผู้สร้างเกม",--CREDITS
menu_credits_help = "ดูรายชื่อผู้ที่สร้างเกมทั้งหมด",--View the credits.
menu_quit = "ออกเกม",--QUIT BUTTON
menu_quit_help = "ออกจากเกม",--Exit the game.
menu_resume_game = "ปฏิบัติภารกิจต่อ",--RESUME GAME
menu_restart_game = "เริ่มภารกิจใหม่",--RESTART GAME
menu_restart_level = "เริ่มภารกิจใหม่",--Restart
menu_restart_vote = "โหวตเริ่มภารกิจใหม่",--Vote Restart
menu_abort_mission = "ยกเลิกการจ้างงาน",--Terminate contract
menu_end_game = "ออกไปหน้าแรก",--QUIT TO MAIN MENU
menu_back = "กด [ESC] เพื่อย้อนกลับ",--BACK [ESC]
menu_announcements = "ประชาสัมพันธ์:",--Announcements:
menu_cash = "จำนวนเงิน: $money;",--Cash: $money;
menu_spendable_skill_points = "จำนวนพ้อยท์ที่เหลือ: $points; พ้อยท์",--Unspent skill points: $points;
hud_offshore_account = "เงินนอกระบบ",
menu_challenge_new = "งานพิเศษ",--Side Jobs
pd2stats_players_button = "เช็คสถานะผู้เล่น",--Player
debug_chat_say = "พูดคุย:",--Chat:
menu_cn_quickplay = "หาห้องเล่นอย่างรวดเร็ว",--QuickPlay