["base_options_menu_lua_mods"] = "Lua 모드", --base_options_menu_lua_mods
["base_options_menu_lua_mods_desc"] = "설치한 Lua 모드의 상태를 확인하고 활성/비활성화할지를 선택할 수 있습니다.", --base_options_menu_lua_mods_desc
["base_options_menu_keybinds"] = "모드 키설정", --base_options_menu_keybinds
["base_options_menu_keybinds_desc"] = "Lua 모드에서 사용하는 기능의 키를 설정합니다.", --base_options_menu_keybinds_desc
["base_options_menu_lua_mod_options"] = "모드 옵션", --base_options_menu_lua_mod_options
["base_options_menu_lua_mod_options_desc"] = "설치한 각각의 Lua 모드를 설정합니다.", --base_options_menu_lua_mod_options_desc
["base_mod_info_version"] = "버전", --base_mod_info_version
["base_mod_info_author"] = "제작자", --base_mod_info_author
["base_mod_info_contact"] = "연락처", --base_mod_info_contact
["base_mod_info_path"] = "설치경로", --base_mod_info_path
["base_mod_info_keybinds"] = "모드 전용 사용하는 키", --base_mod_info_keybinds
["base_mod_info_prehooks"] = "Pre-Hooks", --base_mod_info_prehooks
["base_mod_info_hooks"] = "Hooks", --base_mod_info_hooks
["base_mod_info_persist"] = "Persistent Scripts", --base_mod_info_persist
["base_mod_info_disabled"] = "비활성화 상태", --base_mod_info_disabled
["base_mod_info_to_be_disabled"] = "게임을 재시작한 이후 비활성화 됩니다", --base_mod_info_to_be_disabled
["base_mod_info_to_be_enabled"] = "게임을 재시작한 이후 활성화 됩니다", --base_mod_info_to_be_enabled
["base_mod_info_disabled_impossible"] = "비활성화 할 수 없습니다", --base_mod_info_disabled_impossible
["base_mod_info_no_name"] = "모드 이름 없음", --base_mod_info_no_name
["base_mod_info_no_desc"] = "모드 설명 없음", --base_mod_info_no_desc
["base_mod_info_no_author"] = "제작자 설명 없음", --base_mod_info_no_author
["base_mod_info_no_contact"] = "연락처 없음", --base_mod_info_no_contact
["base_mod_info_no_keybinds"] = "모드 전용 사용하는 키 없음", --base_mod_info_no_keybinds
["base_mod_info_no_hooks"] = "No Hooks", --base_mod_info_no_hooks
["base_mod_info_no_prehooks"] = "No Pre-Hooks", --base_mod_info_no_prehooks
["base_mod_info_no_persist_scripts"] = "No Persistent Scripts", --base_mod_info_no_persist_scripts
["base_mod_notifications_none"] = "No Notifications", --base_mod_notifications_none
["base_mod_notifications_prev"] = "<", --base_mod_notifications_prev
["base_mod_notifications_next"] = ">", --base_mod_notifications_next
["base_mod_notifications_count"] = "$current;/$max;", --base_mod_notifications_count
["base_mod_updates_all_up_to_date"] = "모든 모드의 버전이 최신입니다!", --base_mod_updates_all_up_to_date
["base_mod_updates_updates_required"] = "$count;개의 업데이트가 가능합니다", --base_mod_updates_updates_required
["base_mod_updates_updates_required_row"] = "$mod;", --base_mod_updates_updates_required_row
["base_mod_updates_click_manager"] = "[여기를 눌러 업데이트 매니저를 확인하세요]", --base_mod_updates_click_manager
["base_mod_updates_update_all"] = "모든 Mod 업데이트", --base_mod_updates_update_all
["base_mod_automically_check_for_updates"] = "$mod_name; 업데이트", --base_mod_automically_check_for_updates
["base_mod_automically_check_for_updates_desc"] = "매번 게임을 시작할 때 마다 $mod_name;의 새버전이 있는지 확인합니다", --base_mod_automically_check_for_updates_desc
["base_mod_check_for_updates_now"] = "지금 $mod_name; 업데이트 하기", --base_mod_check_for_updates_now
["base_mod_check_for_updates_now_desc"] = "지금 바로 $mod_name;의 새버전이 있는지 확인합니다", --base_mod_check_for_updates_now_desc
["base_mod_updates_show_update_available"] = "$mod_name;의 새버전이 존재합니다", --base_mod_updates_show_update_available
["base_mod_updates_show_update_available_message"] = "$mod_name;의 새버전이 존재합니다!\n왼쪽 아래에 있는 업데이트 매니저를 통해 자동으로 다운로드 할 수 있습니다!", --base_mod_updates_show_update_available_message
["base_mod_updates_update_mod_now"] = "지금 $mod_name; 업데이트 하기", --base_mod_updates_update_mod_now
["base_mod_update_update_available"] = "$mod_name;의 업데이트가 존재합니다!\n지금 $mod_name;의 새버전을 다운로드 하시겠습니까?", --base_mod_update_update_available
["base_mod_updates_open_update_manager"] = "업데이트 매니저 열기", --base_mod_updates_open_update_manager
["base_mod_updates_open_update_notes"] = "패치 노트 보기", --base_mod_updates_open_update_notes
["base_mod_updates_update_now"] = "지금 업데이트 하기", --base_mod_updates_update_now
["base_mod_updates_update_later"] = "나중에 업데이트 하기", --base_mod_updates_update_later
["base_mod_updates_show_multiple_update_available"] = "여러개의 업데이트가 존재합니다", --base_mod_updates_show_multiple_update_available
["base_mod_updates_show_multiple_update_available_message"] = "다음 모드들의 업데이트가 존재합니다:\n$mods;\n왼쪽 아래에 있는 업데이트 매니저를 통해 업데이트 할 수 있습니다!", --base_mod_updates_show_multiple_update_available_message
["base_mod_updates_update_all_now"] = "모든 모드 업데이트하기", --base_mod_updates_update_all_now
["base_mod_update_no_update_available_title"] = "$mod_name;은(는) 최신입니다!", --base_mod_update_no_update_available_title
["base_mod_update_no_update_available"] = "이미 $mod_name;의 최신버전을 가지고 있습니다.\n정말로 $mod_name;을(를) 재설치 하시겠습니까?\n\n예를 누르면 재설치를 하지 않습니다.", --base_mod_update_no_update_available
["base_mod_update_no_update_available_no_data"] = "이미 $mod_name;의 최신버전을 가지고 있습니다.", --base_mod_update_no_update_available_no_data
["base_mod_update_no_update_available_force"] = "강제로 재설치합니다", --base_mod_update_no_update_available_force
["base_mod_download_downloading_mod"] = "$mod_name; 다운로드 중", --base_mod_download_downloading_mod
["base_mod_download_download_progress"] = "다운로드 중: $downloaded; kb / $total; kb", --base_mod_download_download_progress
["base_mod_download_download_progress_extract"] = "아카이브 추출 중...", --base_mod_download_download_progress_extract
["base_mod_download_download_progress_complete"] = "다운로드 완료 게임을 재시작해 주세요!", --base_mod_download_download_progress_complete
["base_mod_download_download_progress_failed"] = "다운로드 실패 다시 시도해 주세요! :(", --base_mod_download_download_progress_failed
["blt_options_menu_blt_mods"] = "BLT 모드", --BLT Mods
["blt_options_menu_blt_mods_desc"] = "설치된 BLT 모드들을 업데이트하고 관리합니다", --Update and manage your installed BLT mods
["blt_options_menu_lua_mod_options"] = "모드 옵션", --Mod Options
["blt_options_menu_lua_mod_options_desc"] = "설치된 BLT 모드들을 개별적으로 설정합니다", --Configure and customize your installed BLT mods
["blt_options_menu_keybinds"] = "모드 키설정", --Mod Keybinds
["blt_options_menu_keybinds_desc"] = "BLT 모드에서 사용하는 기능의 키를 설정합니다.", --Set your keybinds for your BLT mods
["blt_mod_outdated"] = "이 모드는 구버전 BLT를 기반으로 만들어져 더 이상 지원하지 않습니다. 제작자가 이 모드를 최신버전의 BLT에 맞춰 업데이트 해야 만 합니다. 이 모드를 그대로 두면 예상치 못한 에러나 크래쉬가 발생할 수 있습니다.", --This mod is for an older BLT version and is no longer supported; the developer must update this mod to the latest version of the BLT. You will get errors and crashes by leaving this mod installed.
["blt_mod_missing_dependencies"] = "이 모드는 미리 필요한 모드가 설치되어있지 않아서 사용할 수 없습니다.", --This mod requires other mods to function which are not installed, so it has been disabled.
["blt_mod_missing_dependency"] = "    필요한 모드: $dependency;", --    Missing: $dependency
["blt_mod_missing_dependency_download"] = "    필요한 모드: $dependency;, 다운로드 매니저에 추가되었습니다", --    Missing: $dependency, added to Download Manager
["blt_mod_dependency_disabled"] = "이 모드는 미리 필요한 모드가 비활성화 되어있어서 사용할 수 없습니다.", --This mod requires other mods which are not enabled, so it has been disabled.
["blt_mod_disabled_dependency"] = "    필요한 모드: $dependency;", --    Disabled: $dependency
["blt_mod_info_author"] = "제작자", --Author
["blt_mod_info_contact"] = "연락처", --Contact
["blt_mod_state_enabled"] = "활성화", --Enabled
["blt_mod_state_enabled_desc"] = "게임을 시작하면 이 모드를 사용합니다.", --This mod is loaded when the game is started.
["blt_mod_state_disabled"] = "비활성화", --Disabled
["blt_mod_state_disabled_desc"] = "이 모드를 게임에서 사용하지 않습니다", --This mod will not be loaded by the game.
["blt_mod_state_forced_disabled"] = "비활성화", --Disabled
["blt_mod_state_forced_disabled_desc"] = "이 모드는 버전이 오래되어 게임에서 사용할 수 없습니다.", --This mod is outdated and can not be loaded by the game.
["blt_mod_state_enabled_on_restart"] = "재시작시 활성화", --Enabled On Restart
["blt_mod_state_enabled_on_restart_desc"] = "이 모드를 다음에 게임이 시작할 때부터 사용합니다.", --This mod will be loaded next time the game is started.
["blt_mod_state_disabled_on_restart"] = "재시작시 비활성화", --Disabled On Restart
["blt_mod_state_disabled_on_restart_desc"] = "이 모드를 다음에 게임이 시작할 때부터 사용하지 않습니다.", --This mod will not be loaded by the game the next time it is started.
["blt_mod_safemode_enabled"] = "안전 모드:\n활성화", --Safe Mode:\nEnabled
["blt_mod_safemode_enabled_help"] = "대규모 업데이트가 이루어졌을때 튕김현상 방지를 위해 자동으로 비활성화 합니다.", --Disable this mod after major game updates to prevent crashes.
["blt_mod_safemode_disabled"] = "안전 모드:\n비활성화", --Safe Mode:\nDisabled
["blt_mod_safemode_disabled_help"] = "대규모 업데이트가 이루어져도 비활성화 되지 않습니다.", --This mod will not be disabled automatically after major game updates.
["blt_mod_updates_enabled"] = "자동 업데이트:\n활성화", --Automatic Updates:\nEnabled
["blt_mod_updates_enabled_help"] = "자동적으로 PaydayMods 서버에서 최신버전이 있는지 확인합니다.", --Automatically check with the PaydayMods server for newer versions of this mod.
["blt_mod_updates_disabled"] = "자동 업데이트:\n비활성화", --Automatic Updates:\nDisabled
["blt_mod_updates_disabled_help"] = "이 모드는 PaydayMods 서버에서 최신버전이 있는지 확인하지 않습니다.", --This mod will not check with the PaydayMods server for newer versions.
["blt_mod_check_for_updates"] = "업데이트 확인", --Check for Updates
["blt_mod_check_for_updates_desc"] = "PaydayMods 서버에 최신버전이 존재하는지 확인합니다.", --Check for updates with the PaydayMods server right now.
["blt_mod_toggle_dev"] = "개발자 정보 표시", --Toggle Developer Info
["blt_mod_toggle_dev_desc"] = "이 모드의 개발자 정보를 표시합니다/숨깁니다.", --Show/hide developer information for this mod.
["blt_update_mod_title"] = "$name; 업데이트", --$name Update
["blt_update_mod_up_to_date"] = "$name;은(는) 이미 최신버전입니다.", --$name is already up to date.
["blt_update_mod_error"] = "최신버전이 있는지 확인할 수 없었습니다.\n$reason;", --Could not check if the mod is already up to date.\n$reason
["blt_update_mod_available"] = "$name;의 업데이트가 존재합니다! 다운로드 매니저에 추가되었습니다!", --An update to $name is available! It has been added to the Download Manager!
["blt_update_mod_goto_manager"] = "다운로드 매니저 확인", --Go to Download Manager
["blt_update_dll_title"] = "대단히 중요한 업데이트 존재", --Critical Update
["blt_update_dll_text"] = "BLT DLL 파일의 업데이트가 존재합니다. 공식 BLT 모드 사이트에서 직접 설치하여 업데이트하셔야 합니다.\n\n게임의 오류와 튕김현상을 줄일 수 중요한 업데이트이므로, 최대한 빨리 업데이트해 주시길 바랍니다.", --An update is available to the BLT DLL, you will need to update this yourself by downloading and installing it again from the website.\n\nPlease update ASAP as this is a critical update which may fix crashes with your game.
["blt_update_dll_goto_website"] = "PaydayMods 사이트 방문", --Go to PaydayMods Download
["blt_update_later"] = "나중에 업데이트하기", --Update Later
["blt_download_manager"] = "다운로드 매니저", --Download Manager
["blt_download_manager_help"] = "설치된 BLT 모드들을 업데이트합니다.\n제발 모드들좀 업데이트 해주세요.", --Update your BLT Mods.\nFor the love of god update your mods.
["blt_download_ready"] = "다운로드 준비 완료", --Ready to Download
["blt_download_waiting"] = "기다리는 중...", --Waiting...
["blt_download_downloading"] = "다운로드 중... $bytes;b/$total_bytes;b", --Downloading... $bytes;b/$total_bytes;b
["blt_download_saving"] = "디스크 저장 중...", --Saving to disk...
["blt_download_extracting"] = "압축 푸는 중...", --Extracting...
["blt_download_verifying"] = "확인 중...", --Verifying...
["blt_download_failed"] = "실패! 다시 시도하시겠습니까?", --Failed! Try again?
["blt_download_done"] = "완료!", --Done!
["blt_download_dependency"] = "$dependency; : mod;에서 필요로 합니다", --$dependency, required by $mod
["blt_download_all"] = "모두 업데이트하기", --Update All
["blt_checking_updates"] = "업데이트 확인 중", --Checking for Updates
["blt_checking_updates_help"] = "PaydayMods 서버에서 설치된 모드들의 최신버전을 검색하고 있습니다. 잠시만 기다려주세요...", --Checking with the PaydayMods server for updates to your mods, please wait...
["blt_checking_updates_required"] = "업데이트가 필요합니다", --Updates Required
["blt_checking_updates_required_help"] = "설치된 모드 중 업데이트가 가능한 모드가 있습니다. 다운로드 매니저에서 업데이트 하십시오!", --Updates are available for your mods, visit the download manager to update them!
["blt_view_patch_notes"] = "패치 노트 확인", --View Patch Notes
["blt_checking_updates_none_required"] = "업데이트 확인 완료", --Up to Date
["blt_checking_updates_none_required_help"] = "설치된 모든 모드가 최신버전입니다!", --None of your mods need updating!
["blt_language_select"] = "언어", --Language
["blt_language_select_desc"] = "BLT가 기본으로 사용할 언어를 선택합니다\n(한글패치를 사용하면 설정에 무관하게 한글로 표기됩니다)", --Select the language for the BLT to be displayed in
["blt_language_en"] = "English", --English
["blt_language_cht"] = "Chinese (Traditional)", --Chinese (Traditional)
["blt_language_de"] = "German", --German
["blt_language_fr"] = "French", --French
["blt_language_ru"] = "Russian", --Russian
["blt_language_tr"] = "Turkish", --Turkish
["blt_language_id"] = "Indonesian", --Indonesian
["blt_language_it"] = "Italian", --Italian
["blt_language_zh-cn"] = "Chinese", --Chinese
["blt_no_image"] = "모드 사진 없음", --No Image
["blt_no_name"] = "모드 이름 없음", --No Name
["blt_no_desc"] = "모드 설명 없음", --No Description
