--RATS DAY1/Bain/inst
pln_rt1_04_any_01 = "근처에서 염산, 가성소다, 염화수소를 찾아봐.", --You are looking for muriatic acid, caustic soda and hydrogen chloride.
pln_rt1_04_any_02 = "제조를 하려면 화학약품들이 필요해. 염산, 가성소다, 염화수소. 간단하지.", --We need chemicals to cook. Muriatic acid, caustic soda and hydrogen chloride. Easy.
pln_rats_stage1_19_any_01 = "계속 진행하려면 염산을 넣어야 해!", --You need to add the muriatic acid to keep the process going!
pln_rats_stage1_20_any_01 = "계속 진행하려면, 염산을 넣어!", --Add muriatic acid, to continue the process!
pln_rats_stage1_21_any_01 = "계속 진행하려면 가성 소다를 넣어야 해!", --You need to add the caustic soda to keep the process going!
pln_rats_stage1_22_any_01 = "계속 진행하려면 가성 소다를 넣어!", --Add caustic soda to continue the process!
pln_rats_stage1_23_any_01 = "계속 진행하려면 염화 수소를 넣어야 해!", --You need to add the hydrogen chloride to keep the process going!
pln_rats_stage1_24_any_01 = "계속 하려면 염화 수소를 넣어!", --Add hydrogen chloride to continue the process!
pln_rt1_20_any_02 = "음, 좋아... 염, 염산이야. 좀 넣어봐.", --Ah, OK... Muria, muriatic acid. Add more.
pln_rt1_20_any_03 = "좋아, 이제 가성... 아니, 잠깐, 산을 넣어, 염산 말이야.", --OK, so add caustic... No, wait, add acid - muriatic acid.
pln_rt1_20_any_04 = "여... 염산 - 염산을 좀 더 넣어야돼.", --Mu... Muriatic acid - we need some more in there.
pln_rt1_20_any_05 = "제조는 잘 되어가고 있는거 같아, 염산이 좀 필요하긴 하지만.", --Cooking away fine - needs more acid though.
pln_rt1_20_any_06 = "산이야, 친구들, 산. 가져와서 넣어봐.", --Acid, guys, acid. Get some and pour it in there. 
pln_rt1_20_any_07 = "지금 사이트를 보는 중인데... 이 단계에서 산을 사용하라는데... 우리 염산 가지고 있지, 그렇지?", --Looking at this site... Says acid is used in this step... We got muriatic, right?
pln_rt1_20_any_08 = "흠, 그래 가성소다가 아니고... 그래, 이건 산일꺼야. 맞아, 확실해.", --Hm, yeah it is not caustic soda... Yeah. It should be acid. Yep, sure that is it.
pln_rt1_20_any_09 = "내가 100% 장담하건데 지금 필요한건 염산이야. 그냥 넣어.", --I'm 100% it is muriatic acid now. Just add it.
pln_rt1_22_any_02 = "우리고 온도를 높이려면 소다수가 필요하다고 하는데... 좀 이상해. 근처에 뭐 있어?", --Says we need club soda to get this temperature up... Sounds odd. What can you get?
pln_rt1_22_any_03 = "지금 가성의 염기반응이 일어나야해. 좋아, 너희 주변에 소다같은거 있어? 그걸 넣어.", --Caustic basic reaction is now added. OK you got any soda around? Add it.
pln_rt1_22_any_04 = "가성 소다 - 그래, 그거야. 넣어.", --Caustic soda - yep, thats it. Go for it.
pln_rt1_22_any_05 = "가성수소. 액체 형태라는데... 잠깐만... 이거 소다여야하는거 아니야? 맞지?", --Caustic chloride. Says it is liquid form... Wait a minute... Should be soda, right ? 
pln_rt1_22_any_06 = "나도 지금 잘 모르겠는데. 이 사이트에 설명으로는 도저히 이해가 가질 않는군.", --I'm just guessing at this point... These internet descriptions are iffy.
pln_rt1_22_any_07 = "가성 소다 넣어봐... 아니면 염화... 아니 아니, 기다려봐, 소다... 그걸로 넣어, 그래.", --Try caustic soda....Or hydrogen... No no, wait, soda... Go for that. Yeah.
pln_rt1_22_any_08 = "염화 수소가 필요해. 확실해... 아니 잠시만, 소다... 그래, 가성 소다!", --It needs hydrogen chloride, for sure... OK wait, soda... Yeah, caustic soda!
pln_rt1_22_any_09 = "내가 생각하건데 지금 100% 가성 소다가 필요해. 좀 넣어봐.", --I'm 100% it is some caustic soda needed here. Drop some in.
pln_rt1_24_any_02 = "가성수소. 고체 형태의... 잠깐만... 그러면 이거 염화물 아닌가? 그렇지?", --Caustic chloride. Says it is some solid form... Wait a... Should be that hydrogen, right? 
pln_rt1_24_any_03 = "수소물... 이거 기체형태인가.. 고체는 아닐테고... 그걸 넣으라는데. 혹시 가스 탱크 가지고 있어?", --Hydrogen... Is that a gas... Can't be a solid... Says add it. You guys got a gas tank?
pln_rt1_24_any_04 = "이 사이트는 다르게 설명하는데... 염화 소다 수소의 합성물이래. 나도 몰라. 아무거나 넣어봐.", --This site says something else... Chloride soda hydrogen mix. I don't know, go for it - something.
pln_rt1_24_any_05 = "염화 수소가 필요해. 확실해.", --It needs hydrogen chloride - for sure.
pln_rt1_24_any_06 = "염화 수소가 필요해. 확실해.... 아니, 아니 잠시만... 그래, 맞아.", --It needs hydrogen chloride, for sure... No, no wait... Yeah, OK.
pln_rt1_24_any_07 = "젠장, 우린 저 마약 제조사들이 필요했다고. 나같으면 염화 수소로 찍겠어.", --Fuck me, we needed those cooks. I'm going with hydrogen.
pln_rt1_24_any_08 = "젠장, 우린 저 마약 제조사들이 필요했다고. 나같으면 염화 수소로 찍겠어.", --Fuck me, we needed those cooks. I'm going with chloride.
pln_rt1_24_any_09 = "젠장, 우린 저 빌어먹을 마약 제조사들이 필요했다고. 나같으면 가성소다로 찍겠어.", --Fuck me, we needed those damn cooks. I'm going with caustic soda.
pln_rt1_24_any_10 = "100%로 자신하지 못하지만 내 생각엔 지금은 염화 수소야. 그래, 그럴거야.", --I'm not 100% but I think it is hydrogen chloride now. Yep, should be.
--Bain/NEW COOKING DIALOG
pln_rt1_25_15 = "그러니까 염화수소랑 염산이 다른거였군... 흠, 이 직업을 하면 매일 뭔가를 새로 배운다니까.", --So hydrochloric acid was the same thing... huh, you learn something new every day.
pln_rt1_25_16 = "그러니까 수산화나트륨이 그거였군... 흠, 이 직업을 하면 매일 뭔가를 새로 배운다니까.", --So sodium hydroxide was the same thing... huh, you learn something new every day.
pln_rt1_a_01 = "좋아, 그러니까...", --Alright, let's see...
pln_rt1_a_02 = "잠깐만 있어봐...", --Hold on...
pln_rt1_a_03 = "좋아, 이번에 넣어야 할게...", --Okay, what's next...
pln_rt1_a_04 = "그게, 이번 단계에는...", --So, next step iiis...
pln_rt1_a_05 = "이제 우리가 필요한게...", --Now we need...
pln_rt1_a_06 = "좋아, 다음 재료가...", --Alright, next ingredient...
pln_rt1_a_07 = "좋아, 그 다음에 넣어야 할게...", --Okay, what comes after that...
pln_rt1_a_08 = "어... 음...", --Uh... mhm...
pln_rt1_a_09 = "어, 내가 이걸 제대로 읽은게 맞다면... 어...", --Uh, if I read this correctly... uh...
pln_rt1_a_10 = "어, 이게 맞는거겠지...", --Uh, I hope I got this right...
pln_rt1_b1_01 = "염산이야.", --Muriatic acid.
pln_rt1_b1_02 = "염산을 넣어야 해.", --It's muriatic acid.
pln_rt1_b1_03 = "산이야. 염산이야.", --Acid. Muriatic acid.
pln_rt1_b2_01 = "...염산인가?", --...muriatic acid?
pln_rt1_b2_02 = "음, 염산을 넣어보자고.", --Oh I'm going with muriatic acid.
pln_rt1_b2_03 = "염산을 한번 넣어보자.", --We'll go with muriatic acid.
pln_rt1_b2_04 = "...염산인가?", --...muriatic acid?
pln_rt1_c1_01 = "가성소다야.", --Caustic soda.
pln_rt1_c1_02 = "가성소다를 넣어야 해.", --It's caustic soda.
pln_rt1_c1_03 = "소다야. 가성소다야.", --Soda. Caustic soda.
pln_rt1_c2_01 = "...가성소다인가?", --...caustic soda?
pln_rt1_c2_02 = "가성소다를 넣어보자고.", --I'm going with caustic soda.
pln_rt1_c2_03 = "가성소다를 한번 넣어보자고.", --We'll go with caustic soda.
pln_rt1_c2_04 = "...가성소다인가?", --...caustic soda?
pln_rt1_c2_05 = "...가성소다인가?", --...caustic soda?
pln_rt1_c2_06 = "음, 가성소다를 넣어보자고.", --Oh I'm going with caustic soda.
pln_rt1_d1_01 = "염화수소야.", --Hydrogen chloride.
pln_rt1_d1_02 = "염화수소를 넣어야 해.", --It's hydrogen chloride.
pln_rt1_d1_03 = "염화물. 염화수소야.", --Chloride. Hydrogen chloride.
pln_rt1_d2_01 = "...염화수소인가?", --...hydrogen chloride?
pln_rt1_d2_02 = "염화수소를 넣어보자고.", --I'm going with hydrogen chloride.
pln_rt1_d2_03 = "염화수소를 한번 넣어보자고.", --We'll go with hydrogen chloride.
pln_rt1_e_01 = "근처에 내가 말한 재료 없어?", --You got any of that lying around?
pln_rt1_e_02 = "내가 말한걸 찾아서, 집어넣어.", --Find some, and pour it in.
pln_rt1_e_03 = "내가 말한거 어딘가에 있지 않아?", --You got some of that somewhere?
pln_rt1_e_04 = "내가 말한대로 하면 제조가 될꺼야.", --That should get things cooking.
pln_rt1_e_05 = "내가 말한대로 하면 반응이 일어날꺼야.", --That should get the process going.
pln_rt1_e_06 = "내가 말한대로 하면 작업이 진행될꺼야.", --That should get it on.
pln_rt1_e_07 = "찾아서 넣어.", --Go for it.
pln_rt1_e_08 = "찾아서 넣어봐.", --Add it.
pln_rt1_e_09 = "내가 말한걸 넣어.", --Add some.
pln_rt1_e_10 = "그걸 넣으면 될꺼야.", --Pour it in.
pln_rt1_f_01 = "방금 말한건 아니고...", --Strike that...
pln_rt1_f_02 = "잠깐만!", --Hold up!
pln_rt1_f_03 = "아냐, 잠깐!", --No, wait!
pln_rt1_f_04 = "아냐, 그게 아니야!", --Nope, that's not it!
pln_rt1_f_05 = "잠깐만 기다려봐...", --Wait a second...
pln_rt1_f_06 = "잠깐만 있어봐!", --Wait a minute!
pln_rt1_f_07 = "미안, 방금 말한게 아니야.", --Sorry, that wasn't right.
pln_rt1_f_08 = "잠깐!", --Wait!
pln_rt1_f_09 = "잠깐만! 너희들 그거 아직 안넣었지?", --Hold it! You didn't put it in yet, right?
pln_rt1_f_10 = "썅! 잠깐!", --Shit!
pln_rt1_g_01 = "염산을 넣는거였어!", --It's supposed to be muriatic acid!
pln_rt1_g_02 = "염산을 넣어야 해!", --It should be muriatic acid!
pln_rt1_g_03 = "염산을 넣어야 하는거였어!", --That should'a been muriatic acid!
pln_rt1_g_04 = "염산이 필요해!", --We need muriatic acid!
pln_rt1_g_05 = "그래, 산이야, 염산을 넣는거야.", --Yeah it's acid, muriatic acid.
pln_rt1_g_06 = "내가 실수했어. 염산을 넣어야 해.", --My bad. It's muriatic acid.
pln_rt1_g_07 = "내가 잘못했군. 산을 넣어야 해.", --I messed up. It should'a been acid.
pln_rt1_g_08 = "소거법에 따르면 염산을 넣어야 해.", --By method of elimination it has to be muriatic acid.
pln_rt1_h_01 = "가성소다를 넣는거였어!", --It's supposed to be caustic soda!
pln_rt1_h_02 = "가성소다를 넣어야 해!", --It should be caustic soda!
pln_rt1_h_03 = "가성소다를 넣어야 하는거였어!", --That should'a been caustic soda!
pln_rt1_h_04 = "가성소다가 필요해!", --We need caustic soda!
pln_rt1_h_05 = "그래, 소다야, 가성소다를 넣는거야.", --Yeah it's soda, caustic soda.
pln_rt1_h_06 = "내가 실수했어. 가성소다를 넣어야 해.", --My bad. It's caustic soda.
pln_rt1_h_07 = "내가 잘못했군. 소다를 넣어야 해.", --I messed up. It should'a been soda.
pln_rt1_h_08 = "소거법에 따르면 가성소다를 넣어야 해.", --By method of elimination it has to be caustic soda.
pln_rt1_i_01 = "염화수소를 넣는거였어!", --It's supposed to be hydrogen chloride!
pln_rt1_i_02 = "염화수소를 넣어야 해!", --It should be hydrogen chloride!
pln_rt1_i_03 = "염화수소를 넣어야 하는거였어!", --That should'a been hydrogen chloride!
pln_rt1_i_04 = "염화수소가 필요해!", --We need hydrogen chloride!
pln_rt1_i_05 = "그래, 염화물이야, 염화수소를 넣는거야.", --Yeah it's chloride, hydrogen chloride.
pln_rt1_i_06 = "내가 실수했어. 염화수소를 넣어야 해.", --My bad. It's hydrogen chloride.
pln_rt1_i_07 = "내가 잘못했군. 염화수소를 넣어야 해.", --I messed up. It should'a been hydrogen chloride.
pln_rt1_i_08 = "소거법에 따르면 염화수소를 넣어야 해.", --By method of elimination it has to be hydrogen chloride.
pln_rt1_j_01 = "...그럴꺼야.", --...I think.
pln_rt1_j_02 = "...그럴...꺼야.", --...I... think.
pln_rt1_j_03 = "...내 계산이 맞다는 가정 하에 말이지.", --...IF my calculations are correct.
pln_rt1_j_04 = "...그럴꺼야, 아마도.", --...I think so, at least.
pln_rt1_j_05 = "...내가 빠트린게 없다는 가정 아래에 말이지...", --...unless I've missed something...
pln_rt1_j_06 = "...그래, 확신해. 그럴꺼야.", --...I'm sure. I'm pretty sure.
pln_rt1_j_07 = "...그럴꺼야. 그럴 가능성이 높을꺼야.", --...for sure. Or, most likely.
pln_rt1_j_08 = "...적어도 내 생각은 그래.", --...that's my best guess.
pln_rt1_j_09 = "...적어도 내가 생각하기에는 그래.", --...that's my very best guess.
pln_rt1_j_10 = "...이게 맞을수 밖에 없을꺼야.", --...it has to be.
pln_rt1_j_11 = "...이봐, 마약 제조가 내 특기는 아니라고.", --...this is not my forte.
pln_rt1_j_12 = "...이봐, 화학이 내 전공은 아니었다고.", --...this isn't my specialty, really.
pln_rt1_j_13 = "...이 사이트가 정확하길 빌어야지.", --...this website better be accurate.
pln_rt1_j_14 = "...아무리 일이 잘못되어봤자 무슨일 생기겠어?", --...what's the worst that could happen, right?
pln_rt1_j_15 = "...이 사이트는 설명을 어떻게 이렇게 어렵게 하는건지 참.", --...these internet descriptions are iffy at best.
pln_rt1_j_16 = "...그래... 그래.", --...yeah... yeah.
pln_rt1_j_17 = "...라고 맞기를 기도하는수 밖에.", --...and cross your fingers.
pln_rt1_j_18 = "...라고 행운을 빌어야지.", --...and kiss your lucky charms.
pln_rt1_j_19 = "...라고 50%밖에 장담할 수가 없어.", --...it's a toss-up, really.
pln_rt1_j_20 = "...라고 93%는 장담하지.", --...I'm 93% sure.
pln_rt1_j_21 = "...라고 91%는 장담하지.", --...I'm 91% sure.
pln_rt1_j_22 = "...라고 86%는 장담하지.", --...I'm 86% sure.
pln_rt1_j_23 = "...라고 84%는 장담하지.", --...I'm 84% sure.
pln_rt1_j_24 = "...라고 79%는 장담하지.", --...I'm 79% sure.
pln_rt1_j_25 = "...라고 72%는 장담하지.", --...I'm 72% sure.
pln_rt1_j_26 = "...라고 68%는 장담하지.", --...I'm 68% sure.
pln_rt1_j_27 = "...라고 65.5%는 장담하지.", --...I'm 65.5% sure.
pln_rt1_j_28 = "...라고 57%는 장담하지.", --...I'm 57% sure.
