local text_original = LocalizationManager.text
local testAllStrings = false
function LocalizationManager:text(string_id, ...)
return string_id == "bm_wp_tecci_m_cmag" and "Beta C-Magazine"                    
or string_id == "bm_wp_upg_vg_tac"    and "Tactical Grip"                      
or string_id == "bm_wp_upg_vg_stubby"     and "Stubby Grip"                              
or string_id == "bm_wp_upg_vg_afg"       and "AFG Grip"                                
or string_id == "bm_wp_mp5_s_sold"      and "Solid Stock"
or string_id == "bm_wp_mp5_m_drum"    and "50 Round Drum Magazine"                      
or string_id == "bm_wp_rpk_ban_mag"     and "RPK Banana Magazine"                              
or string_id == "bm_wp_upg_a_slugs"       and "Slug Rounds"                                
or string_id == "bm_wp_upg_a_sniper"       and "Sniper Kit"                                
or string_id == "bm_wp_upg_a_minishell"    and "Minishell Buckshot"                                
or string_id == "bm_wp_upg_a_minishellslug"    and "Minishell Slug"                                
or string_id == "bm_wp_upg_a_customx4"   and "4/0 Buckshot"                                            
or string_id == "bm_wp_upg_a_blank"    and "Blank Rounds"                                
or string_id == "bm_wp_boot_o_iron"    and "Improved Iron Sights"                                
or string_id == "bm_wp_r870_b_legend"    and "Hang Eleven Body"                                
or string_id == "bm_wp_p90_b_legend"    and "Bowie Barrel"                                
or string_id == "bm_wp_upg_s_none"    and "No Stock"                                
or string_id == "bm_wp_scar_a_l"    and "SCAR-L Kit"                                
or string_id == "bm_wp_tecci_s_short"    and "Short Stock"                                
or string_id == "bm_wp_model70_s_legends"    and "Bubba Stock"                                
or string_id == "bm_wp_svinet_s_legend"    and "Lone Wolf Stock"                                
or string_id == "bm_wp_svinet_b_standard"    and "Lone Wolf Barrel"                                
or string_id == "bm_wp_rpg7_m_rocket"    and "The Last Grin"                                
or string_id == "bm_wp_m16_fg_legend"    and "Rail Driver Module"                                
or string_id == "bm_wp_m16_s_legend"    and "Rail Driver Stock"                                
or string_id == "bm_wp_upg_ass_74_s_legend"    and "Dimitri Stock"                                
or string_id == "bm_wp_judge_b_legend"    and "Fisticuff Barrel"                                
or string_id == "bm_wp_judge_g_legend"    and "Leather Grip"                                
or string_id == "bm_wp_deagle_b_legend"    and "Midas Barrel"                                
or string_id == "bm_wp_1911_fl_legendary"    and "Killer Terminator Laser"
or string_id == "bm_wp_model70_b_legends"    and "Short Barrel"                      
or string_id == "bm_wp_m134_barrel_legendary"    and "Dominator Barrel"                      
or string_id == "bm_wp_1911_g_legendary"    and "Coal Grip"                                
or string_id == "bm_wpn_fps_upg_o_akimbo"    and "Akimbo Iron Sights"                                
or string_id == "bm_wp_boot_fg_legend"    and "Sons of The Dammed Body"                                
or string_id == "bm_wp_upg_a_default"    and "Default Non-AP DMR"                                
or string_id == "bm_wp_upg_ass_74_g_legend"    and "Vlad's Fist"                                
or string_id == "bm_wp_upg_ass_74_fg_legend"    and "Vlad's Revenge"                                
or string_id == "bm_wp_m134_body_upper_spikey"    and "Dominatrix Kit"                                
or string_id == "bm_wp_upg_a_sniper_desc"      and "##Adds Armor Piercing Rounds.## \n\n**Decreases Ammo Pickup Rate.**"    
or string_id == "bm_wp_upg_a_slugs_desc"      and "Accurate single pellet that allows you to shoot as far as you please."    
    

or testAllStrings == true and string_id
or text_original(self, string_id, ...)	
end